# Database configuration for Neo4j Data Loader
database:
  postgres: |
    host: 4.150.184.135
    port: 5432
    database: SERP_TREND_DEV_DB
    user: serptrend_user
    password: SERPTREND_1349_SCRAPING
  neo4j: |
    host: localhost
    port: 7687
    database: neo4j
    user: neo4j
    password: password123

queries:
  trending: 'SELECT * from structured_content limit 10;'

# Neo4j Data Loading Configuration
neo4j_load_config:
  # Batch processing settings
  batch_size: 1000
  
  # Vector embedding settings
  embedding:
    model_name: "all-MiniLM-L6-v2"
    chunk_size: 512
    chunk_overlap: 50
    use_llm_chunking: true
    content_properties:
      - "content"
      - "summary"
      - "description"
  
  # OpenAI LLM settings for intelligent chunking
  openai:
    model: "gpt-3.5-turbo"
    max_tokens: 2000
    temperature: 0.1
    api_key_env: "OPENAI_API_KEY"  # Environment variable name for API key
  
  # MCP Neo4j Cypher service settings
  mcp_service:
    enabled: true
    host: "localhost"
    port: 8080
    timeout: 30
  
  # Data validation settings
  validation:
    skip_null_ids: true
    validate_required_fields: true
    max_retries: 3
  
  # Performance settings
  performance:
    parallel_processing: false
    connection_pool_size: 10
    transaction_timeout: 60