# Satellite Analysis Configuration File
# This file contains all configurable parameters for the multi-location analysis

# API Credentials
api_credentials:
  sentinel_hub:
    client_id: "1ecf7748-4066-4ba1-a3df-3ea2517cf7f6"
    client_secret: "lCK9t1qjeD1mKjcmW9sZ1wqMCFwD1RsQ"
    base_url: "https://services.sentinel-hub.com"

# Analysis Parameters
analysis:
  # Property division size (in acres)
  square_size_acres: 1.0  # Options: 0.1, 0.25, 1.0, 2.0, etc.
  
  # Region type for adaptive thresholds
  region_type: "mixed"  # Options: "urban", "rural", "mixed"
  
  # Quality control settings
  quality:
    min_quality_score: 0.7
    min_temporal_consistency: 0.8

# Sentinel Hub API Settings
sentinel_hub:
  # Data source configuration
  data_source:
    type: "sentinel-2-l2a"  # Options: "sentinel-2-l1c", "sentinel-2-l2a"
    crs: "http://www.opengis.net/def/crs/EPSG/0/4326"
  
  # Image processing settings
  image_settings:
    width: 256
    height: 256
    timeout_seconds: 60
  
  # Data filtering
  data_filter:
    max_cloud_coverage: 15  # Percentage
    mosaicking_order: "leastCC"  # leastCC, mostRecent, leastRecent
  
  # Authentication
  authentication:
    grant_type: "client_credentials"
    token_endpoint: "/oauth/token"
    process_endpoint: "/api/v1/process"

# Custom Date Periods
# Leave empty to use default periods (last 28 days)
# Or specify custom periods for analysis
custom_periods:
  enabled: true
  periods:
    - start_date: "2023-08-09"
      end_date: "2023-08-16"
    - start_date: "2025-08-02"
      end_date: "2025-08-09"

# Default periods (used when custom_periods.enabled = false)
default_periods:
  time_range_days: 14
  number_of_periods: 3
  period_overlap_days: 7

# Thresholds for significance determination
thresholds:
  # Base thresholds for different region types
  urban:
    ndvi: 0.3
    ndbi: 0.1
    ndwi: -0.1
  rural:
    ndvi: 0.5
    ndbi: -0.1
    ndwi: 0.1
  mixed:
    ndvi: 0.4
    ndbi: 0.0
    ndwi: 0.0
  
  # Standard deviation limits for reliability
  max_std_dev:
    ndvi: 0.25
    ndbi: 0.20
    ndwi: 0.25

# NDVI Inference Thresholds
ndvi_inference:
  high_vegetation: 0.6
  moderate_vegetation: 0.4
  low_vegetation: 0.2
  very_low_vegetation: 0.0

# NDBI Inference Thresholds
ndbi_inference:
  high_builtup: 0.2
  moderate_builtup: 0.1
  low_builtup: 0.0
  very_low_builtup: -0.1

# NDWI Inference Thresholds
ndwi_inference:
  high_water: 0.3
  moderate_water: 0.1
  low_water: 0.0
  very_low_water: -0.2

# Output Settings
output:
  # Directory structure
  base_directory: "./output"
  timestamp_format: "%Y%m%d_%H%M%S"
  
  # File naming
  files:
    csv_results: "optimized_satellite_analysis_results.csv"
    combined_kml: "enhanced_significant_indices_squares.kml"
    ndvi_kml: "NDVI_Vegetation_Analysis.kml"
    ndbi_kml: "NDBI_BuiltUp_Analysis.kml"
    ndwi_kml: "NDWI_Water_Analysis.kml"
    summary: "analysis_summary.txt"
  
  # KML styling
  kml_styles:
    ndvi:
      color: "ff0000ff"  # Blue
      width: "3"
    ndbi:
      color: "ff0000ff"  # Red
      width: "3"
    ndwi:
      color: "ff00ffff"  # Yellow
      width: "3"

# Sample Input Data
# This can be overridden when calling the script
sample_data:
  lp_no: 2
  extent_ac: 20.49
  point_id: 1
  easting_x: 340751.55
  northing_y: 1590485.86
  latitude: 14.382015
  longitude: 79.523023

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console_output: true
  file_output: false
