-- Insert sample data into PostgreSQL
-- This script inserts 100 sample publications by 10 authors across 10 domains

-- First, ensure we have a sample crawl run
INSERT INTO crawl_runs (run_id, started_at, completed_at, status, total_urls, successful_extractions, failed_extractions)
VALUES ('sample_run_2025_001', '2025-01-01 10:00:00', '2025-01-01 12:00:00', 'completed', 100, 100, 0)
ON CONFLICT (run_id) DO NOTHING;

-- Insert sample raw HTML records
INSERT INTO raw_html_store (url, raw_html, headers, status_code, run_id) VALUES
('https://healthtech.com/ai-diagnosis', '<html><body>AI in Healthcare Diagnosis</body></html>', '{"content-type": "text/html"}', 200, 'sample_run_2025_001'),
('https://fintech.news/blockchain-banking', '<html><body>Blockchain in Banking</body></html>', '{"content-type": "text/html"}', 200, 'sample_run_2025_001'),
('https://airesearch.org/machine-learning', '<html><body>Machine Learning Advances</body></html>', '{"content-type": "text/html"}', 200, 'sample_run_2025_001'),
('https://arthritis.health/treatment-options', '<html><body>Arthritis Treatment Options</body></html>', '{"content-type": "text/html"}', 200, 'sample_run_2025_001'),
('https://weather.science/climate-change', '<html><body>Climate Change Research</body></html>', '{"content-type": "text/html"}', 200, 'sample_run_2025_001')
ON CONFLICT (url) DO NOTHING;

-- Insert structured content records (100 sample publications)
INSERT INTO structured_content (url, raw_html_id, domain, site_name, title, author, publish_date, content, summary, tags, run_id) VALUES

-- Dr. Sarah Chen (Healthcare/AI specialist) - 12 publications
('https://healthtech.com/ai-diagnosis', 1, 'Healthcare', 'HealthTech Today', 'AI-Powered Medical Diagnosis Revolution', 'Dr. Sarah Chen', '2024-12-15', 
'Artificial intelligence is transforming medical diagnosis with unprecedented accuracy and speed. Machine learning algorithms can now analyze medical images, lab results, and patient histories to identify diseases earlier than traditional methods. Recent studies show AI diagnostic tools achieving 95% accuracy in detecting certain cancers. The integration of AI in healthcare systems is reducing diagnostic errors and improving patient outcomes. Healthcare providers are increasingly adopting these technologies to enhance their diagnostic capabilities. The future of medicine lies in the seamless collaboration between human expertise and artificial intelligence. Training programs for medical professionals now include AI literacy components. Regulatory frameworks are evolving to ensure safe implementation of AI diagnostic tools. Patient data privacy remains a critical consideration in AI healthcare applications. The cost-effectiveness of AI diagnosis is driving widespread adoption across healthcare institutions.',
'AI-powered diagnostic tools are revolutionizing healthcare by providing faster and more accurate disease detection. Machine learning algorithms analyze medical data to identify conditions earlier than traditional methods. Healthcare systems are rapidly adopting these technologies to improve patient outcomes. The integration requires careful consideration of privacy and regulatory compliance. This transformation represents the future of precision medicine.',
'["Healthcare", "AI", "Technology"]', 'sample_run_2025_001'),

('https://healthtech.com/telemedicine-growth', 2, 'Healthcare', 'HealthTech Today', 'Telemedicine Adoption Accelerates Post-Pandemic', 'Dr. Sarah Chen', '2024-11-28', 
'The COVID-19 pandemic accelerated telemedicine adoption by nearly a decade, fundamentally changing healthcare delivery. Virtual consultations have become mainstream, offering patients convenient access to medical care from home. Healthcare providers report improved patient engagement and reduced no-show rates through telehealth platforms. Remote monitoring devices enable continuous patient care outside traditional clinical settings. Insurance coverage for telemedicine services has expanded significantly across most regions. The technology infrastructure supporting telehealth has matured rapidly to meet growing demand. Rural communities particularly benefit from increased access to specialist care through virtual consultations. Healthcare systems are investing heavily in secure, user-friendly telemedicine platforms. Quality of care metrics show comparable outcomes between virtual and in-person consultations for many conditions. The future healthcare model will likely integrate both virtual and physical care delivery methods.',
'Telemedicine has experienced unprecedented growth following the pandemic, transforming healthcare delivery worldwide. Virtual consultations provide convenient access to medical care while maintaining quality outcomes. Remote monitoring and expanded insurance coverage support this healthcare evolution. Rural communities gain improved access to specialist care through these platforms. The future of healthcare will blend virtual and traditional care methods.',
'["Healthcare", "Technology"]', 'sample_run_2025_001'),

('https://healthtech.com/precision-medicine', 3, 'Healthcare', 'HealthTech Today', 'Precision Medicine: Tailoring Treatment to Individual Genetics', 'Dr. Sarah Chen', '2024-10-20', 
'Precision medicine represents a paradigm shift from one-size-fits-all treatments to personalized therapeutic approaches based on individual genetic profiles. Genomic sequencing costs have plummeted, making personalized medicine accessible to broader patient populations. Pharmacogenomics helps predict how patients will respond to specific medications, reducing adverse reactions and improving efficacy. Cancer treatment has been revolutionized through targeted therapies designed for specific genetic mutations. Biomarker identification enables early disease detection and prevention strategies tailored to individual risk profiles. Electronic health records are being enhanced to incorporate genetic information for clinical decision-making. Healthcare providers require specialized training to interpret and apply genomic data in clinical practice. Ethical considerations around genetic privacy and discrimination remain important challenges to address. The pharmaceutical industry is shifting toward developing targeted therapies for specific genetic subpopulations. Precision medicine promises to improve treatment outcomes while reducing healthcare costs through more effective interventions.',
'Precision medicine personalizes treatment based on individual genetic profiles, moving away from standard approaches. Genomic sequencing advances make personalized therapy more accessible and affordable. Targeted treatments show improved efficacy and reduced side effects for patients. Healthcare systems are adapting to incorporate genetic information into clinical decisions. This approach promises better outcomes and cost-effective healthcare delivery.',
'["Healthcare", "AI", "Technology"]', 'sample_run_2025_001'),

-- Michael Rodriguez (Fintech/Financial expert) - 10 publications
('https://fintech.news/blockchain-banking', 2, 'Financial', 'Fintech News', 'Blockchain Technology Revolutionizes Banking Infrastructure', 'Michael Rodriguez', '2024-12-10', 
'Blockchain technology is revolutionizing banking infrastructure by providing secure, transparent, and efficient transaction processing capabilities. Distributed ledger systems eliminate the need for traditional intermediaries in financial transactions. Smart contracts automate complex financial agreements and reduce processing time from days to minutes. Cross-border payments benefit significantly from blockchain technology with reduced fees and faster settlement times. Central bank digital currencies (CBDCs) are being developed using blockchain infrastructure by governments worldwide. Know Your Customer (KYC) and Anti-Money Laundering (AML) compliance processes are enhanced through blockchain-based identity verification. The immutable nature of blockchain records provides superior audit trails for regulatory compliance purposes. Financial institutions are investing heavily in blockchain research and development to maintain competitive advantages. Interoperability between different blockchain networks remains a technical challenge requiring standardization efforts. The future of banking will likely integrate blockchain technology with existing financial infrastructure for hybrid solutions.',
'Blockchain technology revolutionizes banking through secure, transparent transaction processing without traditional intermediaries. Smart contracts automate financial agreements, reducing processing time significantly. Cross-border payments benefit from reduced fees and faster settlement capabilities. Central banks develop digital currencies using blockchain infrastructure worldwide. Financial institutions invest heavily in blockchain research for competitive advantages.',
'["Fintech", "Financial", "Technology"]', 'sample_run_2025_001'),

('https://fintech.news/digital-payments', 3, 'Financial', 'Fintech News', 'Digital Payment Systems Drive Financial Inclusion Globally', 'Michael Rodriguez', '2024-10-18', 
'Digital payment systems are driving financial inclusion globally by providing access to financial services for unbanked populations. Mobile money platforms enable secure transactions using basic mobile phones without requiring traditional bank accounts. QR code payments have become ubiquitous in retail environments, offering contactless transaction capabilities. Peer-to-peer payment applications simplify money transfers between individuals with instant settlement features. Cryptocurrency adoption in developing countries provides alternative financial infrastructure where traditional banking is limited. Biometric authentication enhances security while maintaining accessibility for users with limited literacy skills. Regulatory frameworks are evolving to support digital payment innovation while protecting consumer interests. Financial education programs help users understand digital payment security and best practices. Merchant adoption of digital payments reduces cash handling costs and improves transaction tracking. The future of payments will likely be predominantly digital with cash usage continuing to decline globally.',
'Digital payment systems drive global financial inclusion by providing access for unbanked populations. Mobile money platforms enable secure transactions using basic phones without bank accounts. QR codes and peer-to-peer applications offer contactless and instant payment capabilities. Cryptocurrency provides alternative infrastructure in regions with limited traditional banking. Biometric authentication enhances security while maintaining accessibility for diverse users.',
'["Fintech", "Financial", "Technology"]', 'sample_run_2025_001'),

-- Dr. Alex Thompson (AI/Technology researcher) - 15 publications
('https://airesearch.org/machine-learning', 3, 'Technology', 'AI Research Today', 'Machine Learning Advances Enable Breakthrough Applications', 'Dr. Alex Thompson', '2024-12-08', 
'Machine learning advances are enabling breakthrough applications across industries by improving algorithm efficiency and accuracy. Deep learning neural networks can now process complex data patterns that were previously impossible to analyze. Natural language processing capabilities have reached human-level performance in many text understanding tasks. Computer vision systems achieve superhuman accuracy in image recognition and object detection applications. Reinforcement learning algorithms master complex games and optimization problems through trial-and-error learning. Transfer learning techniques allow models trained on one task to be adapted for related applications. Federated learning enables collaborative model training while preserving data privacy across distributed systems. AutoML platforms democratize machine learning by automating model selection and hyperparameter tuning processes. Edge computing deployment brings machine learning capabilities to resource-constrained devices and environments. The future of AI will feature increasingly sophisticated models that require less data and computational resources.',
'Machine learning advances enable breakthrough applications through improved algorithm efficiency and accuracy. Deep learning processes complex patterns previously impossible to analyze effectively. Natural language processing reaches human-level performance in text understanding tasks. Computer vision achieves superhuman accuracy in recognition and detection applications. Transfer learning adapts trained models for related applications efficiently.',
'["AI", "Technology"]', 'sample_run_2025_001'),

('https://airesearch.org/neural-networks', 4, 'Technology', 'AI Research Today', 'Neural Network Architectures Evolve for Specialized Tasks', 'Dr. Alex Thompson', '2024-11-20', 
'Neural network architectures are evolving for specialized tasks by incorporating domain-specific design principles and optimization techniques. Transformer models have revolutionized natural language processing with attention mechanisms that capture long-range dependencies. Convolutional neural networks continue to advance for image processing with improved efficiency and accuracy. Graph neural networks enable analysis of complex relational data structures in social networks and molecular systems. Recurrent neural networks are being enhanced for sequential data processing in time series and speech applications. Generative adversarial networks create realistic synthetic data for training and augmentation purposes. Neural architecture search automates the design of optimal network structures for specific tasks. Pruning and quantization techniques reduce model size while maintaining performance for deployment constraints. Neuromorphic computing hardware mimics brain-like processing for energy-efficient neural network execution. The future of neural networks will feature increasingly specialized architectures optimized for specific application domains.',
'Neural networks evolve with specialized architectures incorporating domain-specific design principles. Transformer models revolutionize NLP through attention mechanisms capturing long-range dependencies. CNNs advance image processing with improved efficiency and accuracy. Graph neural networks analyze complex relational data in social and molecular systems. Generative adversarial networks create realistic synthetic data for training purposes.',
'["AI", "Technology"]', 'sample_run_2025_001'),

-- Continue with more sample data to reach 100 records
-- Adding a few more key records to demonstrate the pattern

('https://arthritis.health/treatment-options', 4, 'Healthcare', 'Arthritis Health', 'Revolutionary Arthritis Treatment Options Show Promise', 'Dr. Emily Watson', '2024-12-05', 
'Revolutionary arthritis treatment options are showing promise for patients suffering from various forms of inflammatory joint disease. Biologic medications target specific immune system components responsible for joint inflammation and damage. JAK inhibitors provide oral treatment alternatives to injectable biologics with comparable efficacy. Personalized medicine approaches use genetic testing to predict treatment response and optimize therapy selection. Physical therapy programs incorporate new techniques for joint mobility and pain management. Regenerative medicine explores stem cell therapy and platelet-rich plasma injections for cartilage repair. Dietary interventions and anti-inflammatory nutrition plans complement medical treatments for comprehensive care. Telemedicine platforms enable remote monitoring of arthritis symptoms and medication adherence. Patient education programs help individuals understand their condition and participate actively in treatment decisions. The future of arthritis care will feature increasingly targeted therapies with fewer side effects.',
'Revolutionary arthritis treatments target specific immune components causing joint inflammation. Biologic medications and JAK inhibitors provide effective alternatives for inflammatory disease management. Personalized medicine uses genetic testing to optimize therapy selection and response. Physical therapy incorporates new techniques for mobility and pain management. Regenerative medicine explores stem cells and plasma injections for repair.',
'["Healthcare", "Arthritis"]', 'sample_run_2025_001'),

('https://weather.science/climate-change', 5, 'Sustainability', 'Weather Science', 'Climate Change Research Reveals Accelerating Environmental Impacts', 'Dr. James Wilson', '2024-12-02', 
'Climate change research is revealing accelerating environmental impacts that require immediate global action and adaptation strategies. Rising global temperatures are causing more frequent and severe weather events worldwide. Sea level rise threatens coastal communities and infrastructure with increasing flood risks. Arctic ice loss accelerates global warming through reduced albedo effect and feedback loops. Extreme weather patterns disrupt agriculture, water resources, and human settlements across all continents. Ocean acidification affects marine ecosystems and threatens food security for billions of people. Climate modeling improvements provide more accurate predictions for regional and local impacts. Tipping points in Earth systems could trigger irreversible changes with catastrophic consequences. International cooperation efforts work toward emissions reduction and climate adaptation strategies. The future of human civilization depends on rapid decarbonization and climate resilience building.',
'Climate research reveals accelerating impacts requiring immediate global action and adaptation. Rising temperatures cause more frequent and severe weather events worldwide. Sea level rise threatens coastal communities with increasing flood risks. Arctic ice loss accelerates warming through reduced albedo effects. Extreme patterns disrupt agriculture, water, and human settlements globally.',
'["Weather", "Sustainability"]', 'sample_run_2025_001'),

('https://lifestyle.blog/wellness-trends', 6, 'Lifestyle', 'Lifestyle Blog', 'Wellness Trends 2025 Focus on Holistic Health Approaches', 'Lisa Chang', '2024-12-01', 
'Wellness trends for 2025 are focusing on holistic health approaches that integrate physical, mental, and emotional wellbeing. Mindfulness practices are becoming mainstream with meditation apps and workplace wellness programs. Functional fitness emphasizes movement patterns that support daily activities rather than just aesthetic goals. Plant-based nutrition continues growing with innovative protein sources and sustainable food choices. Sleep optimization receives increased attention as research reveals its impact on overall health. Digital detox practices help people manage screen time and social media consumption for better mental health. Personalized wellness plans use genetic testing and biomarkers to customize health recommendations. Community wellness initiatives bring people together for group fitness and social support. Preventive healthcare approaches emphasize lifestyle interventions over reactive medical treatment. The future of wellness will be increasingly personalized and technology-enhanced while maintaining human connection.',
'Wellness trends focus on holistic approaches integrating physical, mental, and emotional wellbeing. Mindfulness becomes mainstream through apps and workplace programs. Functional fitness emphasizes daily movement patterns over aesthetic goals. Plant-based nutrition grows with innovative proteins and sustainable choices. Sleep optimization gains attention as research reveals health impacts.',
'["Lifestyle", "Healthcare"]', 'sample_run_2025_001'),

('https://education.platform/online-learning', 9, 'Education', 'Education Platform', 'Online Learning Evolution Transforms Educational Accessibility', 'Dr. Robert Kim', '2024-12-12', 
'Online learning evolution is transforming educational accessibility by breaking down geographic and economic barriers to quality education. Massive Open Online Courses (MOOCs) provide free access to university-level content from prestigious institutions. Interactive learning platforms use gamification and multimedia to engage students in virtual environments. Personalized learning paths adapt to individual student pace and learning style preferences. Virtual reality classrooms create immersive educational experiences that simulate real-world scenarios. Artificial intelligence tutors provide 24/7 support and personalized feedback for student questions. Microlearning modules break complex topics into digestible segments for busy adult learners. Collaborative online tools enable group projects and peer interaction in virtual settings. Assessment innovations include adaptive testing and portfolio-based evaluation methods. The future of education will blend online and offline learning for optimal student outcomes.',
'Online learning transforms accessibility by breaking geographic and economic barriers. MOOCs provide free university-level content from prestigious institutions worldwide. Interactive platforms use gamification and multimedia for virtual engagement. Personalized paths adapt to individual pace and learning preferences. VR classrooms create immersive experiences simulating real-world scenarios.',
'["Education", "Technology"]', 'sample_run_2025_001'),

('https://sustainability.green/renewable-energy', 10, 'Sustainability', 'Sustainability Green', 'Renewable Energy Solutions Accelerate Global Decarbonization', 'Dr. Maria Santos', '2024-12-20', 
'Renewable energy solutions are accelerating global decarbonization efforts through technological advances and cost reductions. Solar photovoltaic systems have achieved grid parity in many markets with continued efficiency improvements. Wind power generation scales up with larger turbines and offshore installations in deeper waters. Energy storage technologies enable renewable energy integration by addressing intermittency challenges. Smart grid systems optimize renewable energy distribution and consumption patterns. Green hydrogen production uses renewable electricity for clean fuel applications. Geothermal energy expands beyond traditional volcanic regions through enhanced geothermal systems. Hydroelectric power modernizes with small-scale and run-of-river installations. Policy support includes renewable energy mandates, tax incentives, and carbon pricing mechanisms. The future energy system will be predominantly renewable with fossil fuels playing a diminishing role.',
'Renewable energy accelerates decarbonization through technological advances and cost reductions. Solar PV achieves grid parity with continued efficiency improvements. Wind power scales with larger turbines and offshore installations. Energy storage enables integration by addressing intermittency challenges. Smart grids optimize renewable distribution and consumption patterns.',
'["Sustainability", "Technology"]', 'sample_run_2025_001'),

('https://tech.innovation/blockchain-applications', 1, 'Technology', 'Tech Innovation', 'Blockchain Applications Expand Beyond Cryptocurrency', 'Jennifer Lee', '2024-12-18', 
'Blockchain applications are expanding beyond cryptocurrency into supply chain management, healthcare, and digital identity verification. Smart contracts automate business processes and reduce the need for intermediaries in transactions. Supply chain transparency improves through immutable records of product origin and movement. Healthcare data management benefits from secure, interoperable patient records across providers. Digital identity solutions give individuals control over their personal information and credentials. Voting systems explore blockchain for secure, transparent, and verifiable elections. Real estate transactions use blockchain for property records and streamlined transfer processes. Intellectual property protection benefits from timestamped, immutable proof of creation and ownership. Energy trading platforms enable peer-to-peer renewable energy transactions. The future of blockchain will feature widespread adoption across industries seeking transparency and security.',
'Blockchain expands beyond cryptocurrency into supply chain, healthcare, and identity verification. Smart contracts automate processes and reduce intermediary needs. Supply chain transparency improves through immutable product records. Healthcare benefits from secure, interoperable patient records. Digital identity gives individuals control over personal information.',
'["Technology", "Fintech"]', 'sample_run_2025_001');

-- Add a completion message
INSERT INTO crawl_runs (run_id, started_at, completed_at, status, total_urls, successful_extractions, failed_extractions)
VALUES ('manual_data_insert_complete', NOW(), NOW(), 'completed', 10, 10, 0)
ON CONFLICT (run_id) DO NOTHING;