# Database configuration
database:
  postgres: |
    host: 4.150.184.135
    port: 5432
    database: SERP_TREND_DEV_DB
    user: serptrend_user
    password: SERPTREND_1349_SCRAPING
  neo4j: |
    host: localhost
    port: 7687
    database: neo4j
    user: neo4j
    password: password123

queries:
  trending: 'SELECT * from structured_content limit 2;'

# Text Chunking Configuration
chunking_config:
  enabled: true
  default_chunk_size: 1000
  default_chunk_overlap: 100
  use_llm_chunking: true
  embedding_model: "text-embedding-3-small"
  embedding_dimension: 1536