# Database configuration
database:
  postgres: |
    host: 4.150.184.135
    port: 5432
    database: SERP_TREND_DEV_DB
    user: serptrend_user
    password: SERPTREND_1349_SCRAPING
  neo4j: |
    # host: ai50-neo4j-db-server-987.westus2.cloudapp.azure.com
    host: localhost
    port: 7687
    database: neo4j
    user: neo4j
    # password: jhF7&asjkldfoie489w
    password: password123

queries:
  trending: 'SELECT * from structured_content WHERE status_neo4j = false OR status_neo4j IS NULL;'

# Batch Processing Configuration
batch_config:
  batch_size: 5  # Process 5 records at a time
  enable_status_tracking: true  # Update status_neo4j after each batch

# Text Chunking Configuration
chunking_config:
  enabled: true
  default_chunk_size: 1000
  default_chunk_overlap: 100
  use_llm_chunking: true
  embedding_model: "text-embedding-3-small"
  embedding_dimension: 1536

# Neo4j Model Configuration
neo4j_model_config:
  trending:
    # Columns to include in model creation (if not specified, all columns are used)
    include_columns:
      - id
      - url
      - domain
      - site_name
      - title
      - author
      - publish_date
      - content
      - summary
      - tags
      - language
      - word_count
      - meta_description
      - is_latest
      - run_id
    
    # Node definitions with labels, properties, and node IDs
    nodes:
      - label: "Article"
        node_id_property: "url"
        properties:
          - name: "url"
            type: "string"
            unique: true
          - name: "id"
            type: "string"
            indexed: true
          - name: "title"
            type: "string"
            indexed: true
          - name: "summary"
            type: "text"
          - name: "publish_date"
            type: "datetime"
          - name: "language"
            type: "text"
          - name: "meta_description"
            type: "text"

  
      - label: "Website"
        node_id_property: "domain"
        properties:
          - name: "domain"
            type: "string"
            unique: true
            alias: "site_domain"
          - name: "site_name"
            type: "string"
            alias: "name"
      
      - label: "Author"
        node_id_property: "name"
        properties:
          - name: "name"
            type: "string"
            unique: true

                  
      - label: "Chunk"
        node_id_property: "chunk_id"
        source_content_field: "content"  # Specifies which field to chunk
        chunking_enabled: true           # Enables automatic chunking
        chunking_config:
          chunk_size: 1000               # Size of each chunk in characters for better context 1000 chars
          chunk_overlap: 100             # Overlap between chunks overlap to 10%
          use_llm_chunking: true       # Use simple chunking instead of LLM
        properties:
          - name: "chunk_id"
            type: "string"
            unique: true
          - name: "embedding"
            type: "vector"
            vector_dimension: 1536        # Updated with match openAI output
            vector_similarity: "cosine"
          - name: "chunk_text"
            type: "text"
          - name: "chunk_position"
            type: "integer"
          - name: "created_from_field"
            type: "string"
            default_value: "content"
          - name: "source_id"
            type: "string"              # Links back to the original Article
    
    # Relationships between nodes
    relationships:
      - type: "PUBLISHED_ON"
        start_node: "Article"
        end_node: "Website"
        start_property: "url"
        end_property: "domain"


      - type: "HAS_CHUNK"
        start_node: "Article"
        end_node: "Chunk"
        start_property: "url"
        end_property: "source_id"        # Links to the source Article
        description: "Relationship created by chunking Article content"
        auto_generated: true             # Indicates this is created during chunking process

      
      - type: "WRITTEN_BY"
        start_node: "Article"
        end_node: "Author"
        start_property: "author"
        end_property: "name"

      
      - type: "TAGGED_WITH"
        start_node: "Article"
        end_node: "Tag"
        start_property: "url"
        end_property: "tag_name"
        properties: []
        # This relationship will be created by splitting the tags field
    
    # Extra indexes beyond the default ones
    extra_indexes:
      - node_label: "Article"
        property: "publish_date"
        type: "RANGE"
      - node_label: "Website"
        property: "domain"
        type: "TEXT"
      - node_label: "Chunk"
        property: "embedding"
        type: "VECTOR"
        vector_dimension: 1536
        vector_similarity: "cosine"
      
    
    # Global aliases for common transformations
    global_aliases:
      Article_text: "Article"
      article_title: "title"
      publication_date: "publish_date"
      source_domain: "domain"
    
    # Best Practices Configuration
    best_practices:
      # Use MERGE instead of CREATE for better data integrity
      use_merge_for_nodes: true
      use_merge_for_relationships: true
      
      # Node creation strategy
      node_creation:
        # Use MERGE with only ID property in pattern, then SET other properties
        merge_on_id_only: true
        # Separate SET clause for non-ID properties
        separate_set_properties: true
        
      # Relationship creation strategy  
      relationship_creation:
        # Use MERGE for relationships after MATCH
        merge_relationships: true
        # Include relationship properties in MERGE or separate SET
        merge_with_properties: false
        
      # Performance optimizations
      performance:
        # Use UNWIND for batch operations
        use_unwind_for_batch: true
        # Batch size for large imports
        batch_size: 1000
        
      # Data integrity
      data_integrity:
        # Skip null values in properties
        skip_null_properties: true
        # Validate required properties
        validate_required_properties: true