name: mcp-neo4j-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  
  # Core data science
  - pandas>=2.0.0
  - numpy>=1.24.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - ipykernel>=6.20.0
  
  # Scientific computing
  - scikit-learn>=1.3.0
  - scipy>=1.10.0
  - plotly>=5.15.0
  
  # Database drivers
  - sqlalchemy>=2.0.0
  - psycopg2>=2.9.0
  - pymongo>=4.0.0
  - redis-py>=4.5.0
  
  # Utilities
  - requests>=2.30.0
  - click>=8.1.0
  - tqdm>=4.65.0
  
  # Development
  - pytest>=7.0.0
  - black>=23.0.0
  - flake8>=6.0.0
  
  # Pip-only packages
  - pip:
    - neo4j>=5.0.0
    - py2neo>=2021.2.3
    - neomodel>=5.0.0
    - mcp>=1.0.0
    - fastapi>=0.100.0
    - uvicorn>=0.20.0
    - pydantic>=2.0.0
    - httpx>=0.24.0
    - websockets>=11.0.0
    - asyncio-mqtt>=0.13.0
    - dash>=2.10.0
    - streamlit>=1.25.0
    - python-dotenv>=1.0.0
    - aiohttp>=3.8.0
    - rich>=13.0.0
    - mypy>=1.0.0