engines:
  tesseract:
    enabled: true
    language: "tel"
    config: "--psm 6"
    
  easyocr:
    enabled: true
    languages: ["te", "en"]
    gpu: false
    
  paddleocr:
    enabled: true
    language: "te"
    use_gpu: false
    
  trocr:
    enabled: false
    model_name: "microsoft/trocr-base-printed"
    
  google_vision:
    enabled: false
    api_key_path: "/Users/ravikiranponduri/Desktop/consultingprojects/research/manuscript_Reader/with_kiro/credentials/google_vision_credentials.json"
    
  azure_vision:
    enabled: false
    subscription_key: "your_azure_key"
    endpoint: "https://your-resource.cognitiveservices.azure.com/"
    
  aws_textract:
    enabled: false
    region: "us-east-1"
    access_key: "your_aws_key"
    secret_key: "your_aws_secret"
    
  abbyy:
    enabled: false
    api_key: "your_abbyy_key"
    endpoint: "https://cloud-eu.abbyy.com"
    
  nanonets:
    enabled: false
    api_key: "your_nanonets_key"
    model_id: "your_model_id"
    
  mathpix:
    enabled: false
    app_id: "your_mathpix_id"
    app_key: "your_mathpix_key"