services:
  neo4j:
    image: neo4j:latest
    volumes:
        - ./neo4j/logs:/logs
        - ./neo4j/data:/data
        - ./neo4j/plugins:/plugins
        - ./neo4j/import:/import
        - ./neo4j/cert:/ssl

    environment:
        - NEO4J_AUTH=neo4j/passw0rd
        - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
        # HTTPS Configuration
        - NEO4J_server_https_enabled=true
        - NEO4J_dbms_ssl_policy_https_enabled=true
        # - NEO4J_dbms_connector_https_enabled=true # new
        # - NEO4J_dbms_connector_https_listen__address=localhost:7473 #new 0.0.0.0
        - NEO4J_dbms_ssl_policy_https_base_directory=/ssl/https
        - NEO4J_dbms_ssl_policy_https_private_key=private.key
        - NEO4J_dbms_ssl_policy_https_public_certificate=public.crt
        - NEO4J_dbms_ssl_policy_https_client_auth=NONE
        - NEO4J_dbms_ssl_policy_https_verify_hostname=false
        # Bolt SSL Configuration
        - NEO4J_server_bolt_enabled=true
        - NEO4J_dbms_ssl_policy_bolt_enabled=true
        - NEO4J_dbms_ssl_policy_bolt_base_directory=/ssl/bolt
        - NEO4J_dbms_ssl_policy_bolt_private_key=private.key
        - NEO4J_dbms_ssl_policy_bolt_public_certificate=public.crt
        - NEO4J_dbms_ssl_policy_bolt_client_auth=NONE
        - NEO4J_dbms_ssl_policy_bolt_verify_hostname=false
 
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    restart: unless-stopped
