# Logging Configuration for GraphRAG Retrieval Agent

version: 1
disable_existing_loggers: false

# Formatters define the format of log messages
formatters:
  json:
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s", "module": "%(module)s", "function": "%(funcName)s", "line": %(lineno)d}'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - [%(module)s:%(funcName)s:%(lineno)d] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  simple:
    format: '%(levelname)s - %(name)s - %(message)s'

# Handlers define where log messages are sent
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  
  file_json:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/graphrag-agent.json
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  file_detailed:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/graphrag-agent.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: json
    filename: logs/errors.json
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8

# Loggers define which handlers to use for different parts of the application
loggers:
  graphrag:
    level: DEBUG
    handlers: [console, file_json, file_detailed, error_file]
    propagate: false
  
  graphrag.embedding:
    level: DEBUG
    handlers: [file_json, error_file]
    propagate: false
  
  graphrag.neo4j:
    level: DEBUG
    handlers: [file_json, error_file]
    propagate: false
  
  graphrag.retrieval:
    level: DEBUG
    handlers: [file_json, error_file]
    propagate: false
  
  graphrag.mcp_server:
    level: INFO
    handlers: [console, file_json, error_file]
    propagate: false
  
  # Third-party library loggers
  neo4j:
    level: WARNING
    handlers: [file_detailed]
    propagate: false
  
  sentence_transformers:
    level: WARNING
    handlers: [file_detailed]
    propagate: false

# Root logger configuration
root:
  level: INFO
  handlers: [console, file_detailed]

# Execution tracing configuration
execution_tracing:
  enabled: true
  log_level: INFO
  include_request_id: true
  include_execution_time: true
  trace_file: logs/execution_traces.json